repos:
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    args: [--config, .github/configs/.prettierrc.json]
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.21.0
  hooks:
  - id: eslint
ci:
  autofix_prs: true
  autoupdate_branch: develop
  autoupdate_schedule: weekly
