repos:
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    types_or: [css, javascript]

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.1.0
  hooks:
  - id: eslint
    additional_dependencies:
      - 'eslint@8.1.0'
      - 'babel-eslint@10.1.0'
      - 'eslint-import-resolver-babel-module@5.3.1'
      - 'eslint-import-resolver-webpack@0.13.2'
      - 'eslint-plugin-import@2.25.2'

ci:
  autofix_prs: true
  autoupdate_branch: develop
  autoupdate_schedule: weekly
